import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import PriceChartLayout from './client/PriceChartLayout';
import './globals.css';
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>$ATOM-$NTRN 7-Day Price Chart</title>
        <link rel="stylesheet" href="styles.css" />
      </head>
      <body className={inter.className}>
      
        <PriceChartLayout />
        <Script src="https://cdn.jsdelivr.net/npm/chart.js"></Script>
      </body>
    </html>
  );
}